# Generated by Django 5.0.3 on 2024-04-02 23:59

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_entry_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=pages.models.LowercaseTextField(verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='File Title'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Image Title'),
        ),
    ]
